import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LiquidGlass } from '../../src';
function App() {
  const [blur, setBlur] = useState(3), [color, setColor] = useState(.15), [strength, setStrength] = useState(160);
  const [profile, setProfile] = useState<'material' | 'loupe' | 'player'>('player');
  return <><header><h1>Native glass. Refined optics.</h1><p>Chromium comparison: legacy gradients on the left, the current rounded lens on the right. Scroll the live HTML behind both. No snapshots or scroll-driven rendering.</p><div className="controls"><label>Profile <select aria-label="Profile" value={profile} onChange={e=>setProfile(e.target.value as typeof profile)}><option value="player">Player glass</option><option value="loupe">Magnifying lens</option><option value="material">Navbar material</option></select></label><label>Blur <input aria-label="Blur" type="range" min="0" max="8" step=".5" value={blur} onChange={e => setBlur(+e.target.value)} /></label><label>Color <input aria-label="Color" type="range" min="0" max="1" step=".05" value={color} onChange={e => setColor(+e.target.value)} /></label><label>Lens strength <input aria-label="Lens strength" type="range" min="0" max="320" value={strength} onChange={e => setStrength(+e.target.value)} /></label></div></header><main><h2>Live pixels.<br/>Clear contours.</h2><p>ABCDEFGHIJKLMNOPQRSTUVWXYZ<br/>0123456789</p><div className="block"><h2>Color in motion.</h2></div><p>Sharp text, rounded corners and curved edges.<br/>Scroll back and forth to compare.</p></main><div className="floating">{(['classic','lens'] as const).map(refraction => <LiquidGlass key={refraction} data-testid={refraction} refraction={refraction} lensProfile={profile} effectMode="auto" mirror={false} quality="high" radius={40} scale={refraction === 'lens' ? strength : 160} blur={blur} aberrationIntensity={color} background="transparent" frost={0} saturation={100} style={{width:'100%'}}><div className="glass-content">{refraction === 'lens' ? profile === 'player' ? 'Player glass' : profile === 'loupe' ? 'Magnifying lens' : 'Navbar material' : 'Legacy gradients · diagnostic'}</div></LiquidGlass>)}</div></>;
}
createRoot(document.querySelector('#root')!).render(<App />);
