import {useEffect,useRef,useState} from 'react'
import type {LiquidGlassProps} from 'simple-liquid-glass'
import {GripHorizontal,RotateCcw,Plus,Check} from 'lucide-react'
import StudioGlass from './StudioGlass'

export default function GlassMemo({glassProps={}}:{glassProps?:LiquidGlassProps}){
 const card=useRef<HTMLDivElement>(null),position=useRef({x:0,y:0}),drag=useRef<{id:number,x:number,y:number}|null>(null)
 const [items,setItems]=useState([{id:1,text:'Find a quiet coastline',done:true},{id:2,text:'Take the scenic route',done:false},{id:3,text:'Stay for the sunset',done:false}]),[draft,setDraft]=useState('')
 const move=(x:number,y:number)=>{const el=card.current,parent=el?.parentElement;if(!el||!parent)return;const box=parent.getBoundingClientRect(),rect=el.getBoundingClientRect();const left=rect.left-position.current.x,top=rect.top-position.current.y;const nx=Math.max(box.left-left+12,Math.min(x,box.right-left-rect.width-12)),ny=Math.max(box.top-top+12,Math.min(y,box.bottom-top-rect.height-12));position.current={x:nx,y:ny};el.style.transform=`translate3d(${nx}px,${ny}px,0)`}
 useEffect(()=>{const observer=new ResizeObserver(()=>move(position.current.x,position.current.y));if(card.current?.parentElement)observer.observe(card.current.parentElement);return()=>observer.disconnect()},[])
 return <div ref={card} className="memo-widget"><StudioGlass radius={30} {...glassProps}><div className="memo-inner"><div className="memo-toolbar"><span>FIELD NOTES</span><button className="drag-handle" aria-label="Move checklist. Drag or use arrow keys; Home resets position." onPointerDown={e=>{if(e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={id:e.pointerId,x:e.clientX-position.current.x,y:e.clientY-position.current.y}}} onPointerMove={e=>{if(drag.current?.id===e.pointerId)move(e.clientX-drag.current.x,e.clientY-drag.current.y)}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}} onLostPointerCapture={()=>{drag.current=null}} onKeyDown={e=>{const d=e.shiftKey?24:8;const offsets:Record<string,number[]>={ArrowLeft:[-d,0],ArrowRight:[d,0],ArrowUp:[0,-d],ArrowDown:[0,d]};if(e.key==='Home'){e.preventDefault();move(0,0)}else if(offsets[e.key]){e.preventDefault();move(position.current.x+offsets[e.key][0],position.current.y+offsets[e.key][1])}}}><GripHorizontal size={23}/></button></div><h3>A little less hurry.</h3><p>Your plans, wherever you put them.</p><div className="memo-list">{items.map(item=><label key={item.id} className={item.done?'done':''}><input type="checkbox" checked={item.done} onChange={()=>setItems(v=>v.map(i=>i.id===item.id?{...i,done:!i.done}:i))}/><span className="memo-checkbox">{item.done&&<Check size={13}/>}</span><span>{item.text}</span></label>)}</div><form className="memo-add" onSubmit={e=>{e.preventDefault();if(draft.trim()){setItems(v=>[...v,{id:Date.now(),text:draft.trim(),done:false}]);setDraft('')}}}><input aria-label="New checklist item" placeholder="Make a little plan…" maxLength={60} value={draft} onChange={e=>setDraft(e.target.value)}/><button aria-label="Add checklist item" disabled={!draft.trim()}><Plus size={18}/></button></form><div className="memo-footer"><span>{items.filter(i=>i.done).length} / {items.length} COMPLETE</span><button aria-label="Reset checklist position" onClick={()=>move(0,0)}><RotateCcw size={13}/> Reset position</button></div></div></StudioGlass></div>
}
