import {useEffect,useRef,useState} from 'react';
import Glass from './Glass';
import {Search,X,Phone,MessageCircle,Camera,Globe,CloudSun,ArrowUpRight,Wifi,BatteryFull,Folder} from 'lucide-react';

import {launcherApps as apps} from './launcherApps';
const wallpapers=[{id:'cobalt',name:'Cobalt'},{id:'copper-satin',name:'Copper Satin'},{id:'alpine',name:'Alpine'}];
export default function LiveLauncher(){
 const [wallpaper,setWallpaper]=useState('cobalt'),[query,setQuery]=useState(''),[searching,setSearching]=useState(false),[opened,setOpened]=useState<string|null>(null),[time,setTime]=useState('09:41');
 const backdrop=useRef<HTMLDivElement>(null);
 const input=useRef<HTMLInputElement>(null),close=useRef<HTMLButtonElement>(null),trigger=useRef<HTMLElement|null>(null);
 useEffect(()=>{const update=()=>setTime(new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hour12:false}));update();const timer=setInterval(update,60000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(searching)input.current?.focus()},[searching]);
 useEffect(()=>{if(opened)close.current?.focus()},[opened]);
 const dismiss=()=>{setOpened(null);trigger.current?.focus()};
 const open=(name:string)=>{trigger.current=document.activeElement as HTMLElement;setOpened(name)};
 return <div className="live-demo" id="live-launcher"><div className="launcher-surface" style={{isolation:'isolate'}} onKeyDown={event=>{if(event.key==='Escape'){if(opened)dismiss();else{setSearching(false);setQuery('')}}}}>
  <div ref={backdrop} aria-hidden="true" style={{position:'absolute',inset:0,backgroundImage:`url(/media/web-${wallpaper}.webp)`,backgroundSize:'cover',backgroundPosition:'center 48%',zIndex:-1}}/>
  <div className="launcher-status"><span>{time}</span><span><Wifi size={14}/><BatteryFull size={18}/></span></div>
  <div className="launcher-topline"><div><span className="launcher-date">A LITTLE MORE EVERYDAY.</span><p>Hello, home.</p></div><span className="web-preview">INTERACTIVE WEB PREVIEW · WEB ARTWORK</span></div>
  <div className="launcher-layout" inert={opened?true:undefined}><div className="launcher-widgets"><Glass backdropRef={backdrop} backdropVersion={wallpaper} className="clock-widget"><div className="widget-body"><span>LOCAL TIME</span><strong>{time}</strong><span>Make time for a little wonder.</span></div></Glass><Glass backdropRef={backdrop} backdropVersion={wallpaper} className="weather-widget"><div className="weather-body"><CloudSun size={38} strokeWidth={1}/><div><strong>24°</strong><span>Sample weather widget</span></div></div></Glass></div>
  <div className="launcher-apps">{apps.filter(app=>app.name.toLowerCase().includes(query.toLowerCase())).map(({name,Icon})=><div className="app-item" key={name}><Glass backdropRef={backdrop} backdropVersion={wallpaper} className="app-glass" radius={22}><button onClick={()=>open(name)} aria-label={`Preview ${name}`}><Icon strokeWidth={1.4}/></button></Glass><span>{name}</span></div>)}{!query&&<div className="app-item"><Glass backdropRef={backdrop} backdropVersion={wallpaper} className="app-glass" radius={22}><button onClick={()=>open('Essentials')} aria-label="Open Essentials folder"><span className="mini-folder"><Phone/><MessageCircle/><Globe/><Camera/></span></button></Glass><span>Essentials</span></div>}{query&&!apps.some(a=>a.name.toLowerCase().includes(query.toLowerCase()))&&<p className="no-results">No apps found.</p>}</div></div>
  <div className="launcher-bottom" inert={opened?true:undefined}><Glass backdropRef={backdrop} backdropVersion={wallpaper} className="launcher-search" radius={30}>{searching?<label><Search size={15}/><input ref={input} value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search preview apps" placeholder="Search apps"/><button aria-label="Close search" onClick={()=>{setSearching(false);setQuery('')}}><X size={15}/></button></label>:<button onClick={()=>setSearching(true)}><Search size={15}/>Search</button>}</Glass><Glass backdropRef={backdrop} backdropVersion={wallpaper} className="launcher-dock" radius={30}><div className="dock-apps">{[{name:'Phone',Icon:Phone},{name:'Messages',Icon:MessageCircle},{name:'Browser',Icon:Globe},{name:'Camera',Icon:Camera}].map(({name,Icon})=><button key={name} aria-label={`Preview ${name}`} onClick={()=>open(name)}><Icon size={27} strokeWidth={1.4}/></button>)}</div></Glass></div>
  {opened&&<div className="launcher-dialog" role="dialog" aria-modal="true" aria-label={`${opened} preview`} onKeyDown={e=>{if(e.key==='Tab'){e.preventDefault();close.current?.focus()}}}><div className="dialog-card"><button ref={close} onClick={dismiss} className="dialog-close" aria-label="Close app preview"><X size={20}/></button>{opened==='Essentials'?<><Folder size={32}/><h3>Essentials</h3><div className="folder-preview"><Phone/><MessageCircle/><Globe/><Camera/></div><p>Your favorites, together.</p></>:<><ArrowUpRight size={30}/><h3>{opened}</h3><p>On your phone, this opens the installed app. Here, you’re exploring the launcher’s glass interface.</p></>}</div></div>}
 </div><div className="demo-controls"><div><span className="demo-indicator"/>LIVE GLASS. GO AHEAD, TOUCH IT.</div><div className="wallpaper-switch" role="group" aria-label="Preview wallpaper">{wallpapers.map(w=><button key={w.id} aria-label={`Use ${w.name} wallpaper`} aria-pressed={wallpaper===w.id} onClick={()=>setWallpaper(w.id)} style={{backgroundImage:`url(/media/web-${w.id}.webp)`}}><span>{w.name}</span></button>)}</div></div></div>
}
